# Generated by Django 2.0.4 on 2018-06-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_code', models.IntegerField(default=0)),
                ('items_name', models.CharField(max_length=200)),
                ('items_category', models.IntegerField(default=0)),
                ('items_Cprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('items_time', models.CharField(max_length=200)),
                ('items_Pprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('items_rtn', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
