# Generated by Django 2.0.4 on 2018-06-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='items_time',
            field=models.IntegerField(default=0),
        ),
    ]
