# Generated by Django 2.0.4 on 2018-06-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180619_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='items_Cprice',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='前一天收盤價'),
        ),
        migrations.AlterField(
            model_name='items',
            name='items_Pprice',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='預測收盤價'),
        ),
        migrations.AlterField(
            model_name='items',
            name='items_category',
            field=models.IntegerField(default=0, verbose_name='產業類別'),
        ),
        migrations.AlterField(
            model_name='items',
            name='items_code',
            field=models.IntegerField(default=0, verbose_name='股票代碼'),
        ),
        migrations.AlterField(
            model_name='items',
            name='items_name',
            field=models.CharField(max_length=200, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='items',
            name='items_rtn',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='預測報酬率'),
        ),
        migrations.AlterField(
            model_name='items',
            name='items_time',
            field=models.IntegerField(default=0, verbose_name='預測期間'),
        ),
    ]
